### ISSUE TITLE
Support Rundeck 3.3.x and above

### ISSUE THREAD

**Issue by dingouerinitx** [robertdebock/ansible-role-rundeck#13]
## Proposed feature

Please update this role to use version 3.3.x and above.

* Upgrade Info at <https://docs.rundeck.com/docs/upgrading/upgrading-to-rundeck-3.3.html>

## Rationale

A lot has changed in the changelog from 3.2.x to 3.3.x and it is not out of the box possible to use this role and to make it work with the new version I experienced. I would love to see a role handling the latest rundeck releases.

## Additional context

Additionally you might have experienced as well that the style of the `rundeck_download_url` has slightly changed since version 3.2.9 upwards

```bash
# Old links for version 3.2.6 - 3.2.8
# rundeck_download_url: "https://dl.bintray.com/rundeck/rundeck-maven/rundeck-{{ rundeck_version }}-{{ rundeck_release_date }}.war"

# New links 3.2.9 -
rundeck_download_url: "https://dl.bintray.com/rundeck/rundeck-maven/org/rundeck/rundeck/rundeck-{{ rundeck_version }}-{{ rundeck_release_date }}.war"
```

**Comment by robertdebock** [comment]
I've just released version 3.2.0 of this role, it now installs 3.3.3 and indeed is a little different.

Thanks for the help, let me know if you have issues using this role.

Regards, Robert de Bock.
