### ISSUE TITLE
Support Rundeck v4 

### ISSUE THREAD

**Issue by Lusitaniae** [robertdebock/ansible-role-rundeck#14]
Possibly the role works as is, just need to update the defaults?

https://github.com/rundeck/rundeck/releases

Latest releasae: v4.1.0-20220420

Upgrade notes:
https://docs.rundeck.com/docs/upgrading/upgrading-to-4.html

**Comment by Lusitaniae** [comment]
First time I'm setting up Rundeck, so forgive me if I miss something, I'm seeing a some issues here:

First, all the config/properties are not being loaded by rundeck. After installing it with deb package I see the reason? the profile template is not being installed by the role https://github.com/robertdebock/ansible-role-rundeck/search?q=profile

The file exists in templates, but it's never picked up by any task

**Comment by robertdebock** [comment]
You are correct, I guess I removed it from tasks some moment. Let me work on a fix and push.

**Comment by Lusitaniae** [comment]
Appreciated for the fast turnaround!

**Comment by robertdebock** [comment]
Thanks for your input! Please try release 4.1.0. (Should be on Galaxy in a few minutes)

**Comment by robertdebock** [comment]
I'll close the issue, but if you find the last release needs changes, please let me know!
