### ISSUE TITLE
Rundeck 4.6.1 does not start after installation with error  Unsupported connection setting "MVCC" 

### ISSUE THREAD

**Issue by wouterdt** [robertdebock/ansible-role-rundeck#19]
## Description

Role runs without error but rundeck fails to start
ERROR pool.ConnectionPool [main] - Unable to create initial connections of pool
org.h2.jdbc.JdbcSQLNonTransientConnectionException: Unsupported connection setting "MVCC" [90113-210

```
java -Xmx4g -jar rundeck-4.6.1-20220914.war
<omitted>
ERROR pool.ConnectionPool [main] - Unable to create initial connections of pool
org.h2.jdbc.JdbcSQLNonTransientConnectionException: Unsupported connection setting "MVCC" [90113-210
```
The rundecks server starts when MVCC=true is removed from server/config/rundeck-config.properties
dataSource.url = jdbc:h2:[file:/opt/rundeck/server/data/grailsdb;MVCC=true](file:///opt/rundeck/server/data/grailsdb**;MVCC=true)**

## Playbook

```yaml
- hosts: localhost
  become: true
  roles:
    - geerlingguy.java
    - robertdebock.rundeck

```

## Output

Show at least the error, possible related output, maybe just all the output.

## Environment

java --version
openjdk 11.0.16 2022-07-19 LTS
OpenJDK Runtime Environment (Red_Hat-11.0.16.0.8-1.el8_6) (build 11.0.16+8-LTS)
OpenJDK 64-Bit Server VM (Red_Hat-11.0.16.0.8-1.el8_6) (build 11.0.16+8-LTS, mixed mode, sharing)

    Control node OS: Red Hat Enterprise Linux release 8.6 (Ootpa)
    ansible [core 2.12.2]
    config file = /etc/ansible/ansible.cfg
python version = 3.8.12 (default, Sep 16 2021, 10:46:05) [
GCC 8.5.0 20210514 (Red Hat 8.5.0-3)] jinja version = 3.1.2 libyaml = True
    Managed node OS: Red Hat Enterprise Linux release 8.6 (Ootpa)

Please consider [sponsoring me](https://github.com/sponsors/robertdebock).

**Comment by robertdebock** [comment]
Got it, fixed with the last commit.
