### ISSUE TITLE
ansible_fqdn determines rundeck listening IP Address, not rundeck_address variable.

### ISSUE THREAD

**Issue by insanity54** [robertdebock/ansible-role-rundeck#7]
I'm not sure if this is a bug, but it had me very confused for a bit and I thought I'd document this behavior. Maybe it could help someone out who comes across a similar problem.

Here is an example machine which does not expose rundeck to the outside world because rundeck is listening on a loopback IP address.

### Contents of undesirable `/etc/hosts`

```
127.0.0.1    localhost
127.0.1.1    vultr.guest

# The following lines are desirable for IPv6 capable hosts
::1          localhost ip6-localhost ip6-loopback
ff02::1      ip6-allnodes
ff02::2      ip6-allrouters
```

This this machine runs ansible role with following variables

```
rundeck_port: 8912
rundeck_address: "{{ ansible_default_ipv4.address }}"
```

In this example, ansible_default_ipv4.address is 45.32.207.103. 
In this example, the rundeck systemd file [Service] section is as follows

```
[Service]
ExecStart=/usr/bin/java -Xmx1024m -Xms256m -XX:MaxMetaspaceSize=128m -server -Dserver.web.context=/ -Dserver.http.host=45.32.207.103 -Dserver.http.port=8912 -jar /opt/rundeck/rundeck-3.0.8-20181029.war
```

All that looks fine, but rundeck isn't actually listening on 45.32.207.103, as revealed by `# netstat -tualpn`--

```
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      472/systemd-resolve 
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      643/sshd            
tcp        0     36 155.138.245.81:22       216.229.183.15:56156    ESTABLISHED 6279/sshd: root@pts 
tcp6       0      0 127.0.1.1:8912          :::*                    LISTEN      7021/java           
tcp6       0      0 :::22                   :::*                    LISTEN      643/sshd            
udp        0      0 127.0.0.53:53           0.0.0.0:*                           472/systemd-resolve 
udp        0      0 155.138.245.81:68       0.0.0.0:*                           844/systemd-network 
```

rundeck is listening on loopback address!

It seems that the FQDN is used to derive IP address. In my case, `/etc/hosts` dictates that `vultr.guest` resolves to the IP address I was seeing in netstat output, `127.0.1.1`.

I traced this behavior back to [defaults/main.yml line 26](https://github.com/robertdebock/ansible-role-rundeck/blob/3d3bbf9c46189e2c136e79bbcc3c63e54cff43ad/defaults/main.yml#L26).

Simply, the fix is to set the FQDN before ansible-role-rundeck is invoked, as well as use ansible to update my DNS record on vultr.

### A prerequisite task
```
(...)
- name: Update rundeck.example.com Vultr DNS record
  vultr_dns_record:
    name: rundeck
    domain: example.com
    data: "{{ server.json.main_ip }}"
    ttl: 3600
```

### The role invocations
```
  (...)
  roles:
    - role: holms.fqdn
      fqdn: rundeck.example.com
      hostname: rundeck
    - role: robertdebock.rundeck
```

### Contents of desirable /etc/hosts

```
127.0.0.1    localhost
127.0.1.1    vultr.guest

# The following lines are desirable for IPv6 capable hosts
::1          localhost ip6-localhost ip6-loopback
ff02::1      ip6-allnodes
ff02::2      ip6-allrouters

45.32.207.103 rundeck.example.com rundeck
```

### Final desirable result of `netstat -tualpn`

```
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      471/systemd-resolve 
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      616/sshd            
tcp        0    232 45.32.207.103:22        216.229.183.15:42750    ESTABLISHED 6305/sshd: root@pts 
tcp6       0      0 45.32.207.103:8912      :::*                    LISTEN      6215/java           
tcp6       0      0 :::22                   :::*                    LISTEN      616/sshd            
udp        0      0 127.0.0.53:53           0.0.0.0:*                           471/systemd-resolve 
udp        0      0 45.32.207.103:68        0.0.0.0:*                           844/systemd-network 
```

Rundeck is now accessible to the internet. I'm a happy camper now that I figured out this behavior.

**Comment by robertdebock** [comment]
Thanks for the notification, I'll try reproduce the issue and write a fix for it.

I think you are right though, probably /etc/hosts should be filled.

**Comment by robertdebock** [comment]
Confirmed, I'll update the documentation to include a `common` role to set the hostname and fill /etc/hosts.
